# File: .github/workflows/workflow.yml

on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az extension add -n azure-cli-ml
          az account show
          az ml datastore attach-blob  -n workspaceblobstore -a azure18884857647  -c azureml-blobstore-8d50cb50-8f35-447f-8a6a-64c56a4f4568

          #az storage container set-permission -n CONTAINER_NAME --public-access blob/container/off
          #az storage container show --workspaceblob
          
          #az storage -h
          #az container logs --resource-group 'Azure机器学习' --name 'workspaceblobstore'
