# File: .github/workflows/workflow.yml

on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az extension add -n azure-cli-ml
          az account show
          az storage container set-permission -n CONTAINER_NAME --public-access blob/container/off
          az storage container show --workspaceblob
          
          #az storage -h
          #az container logs --resource-group 'Azure机器学习' --name 'workspaceblobstore'
